Feature/1 by 1 chat
IGogogogogo/Bubblegram pull request #20
Opened 2020-09-08 07:07 UTC by wye139629

可以即時傳送訊息及圖片給其他使用者
目前問題：
傳送圖片時，無法自動跳到最下面

2020-09-09 03:19 UTC, gn2481 approved these changes

2020-09-09 03:45 UTC, gn2481 commented on app/frontend/channels/chat_channel.js
> +          message_text_area.innerHTML += other
message_text_area.innerHTML += **data.other_image**

2020-09-09 03:47 UTC, gn2481 commented
瀏覽器的字體調成鐘以上的時候，input的會蓋到form的外框

2020-09-09 03:52 UTC, gn2481 approved these changes

2020-09-09 03:59 UTC, gn2481 commented
訊息傳送後，當input 清空，有的時候圖片的圖示跳不出來

2020-09-09 06:41 UTC, chiayinin requested changes
搜尋頁。
搜尋到的使用者也有「傳送」按鈕，按下去會噴錯。
「Couldn't find User without an ID」

2020-09-10 12:46 UTC, besquevans approved these changes

2020-09-11 13:21 UTC, chiayinin approved these changes

2020-09-12 03:12 UTC, chiayinin approved these changes

2020-09-12 09:31 UTC, merged